# Generated by Django 5.0.1 on 2024-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_CHECKIN', 'Aguardando realizar o check-in'), ('EM_ESTADIA', 'Em estadia'), ('CHECKOUT_REALIZADO', 'Estadia finalizada')], default='AGUARDANDO_CHECKIN', max_length=20, verbose_name='Status')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail do hospede')),
                ('horario_checkin', models.DateTimeField(verbose_name='Horário da realização do Check-In')),
                ('horario_checkout', models.DateTimeField(auto_now=True, null=True, verbose_name='Horárrio da realização do Check-Out')),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
                'db_table': 'hospede',
            },
        ),
    ]
