# Generated by Django 5.0.1 on 2024-02-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone do hóspede'),
        ),
    ]
