# Generated by Django 5.0.1 on 2024-02-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0002_hospede_telefone'),
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portaria.portaria', verbose_name='Atendente da portaria responsável pelo Check-In'),
        ),
    ]
