# Generated by Django 5.0.1 on 2024-02-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0003_hospede_registrado_por'),
        ('portaria', '0001_initial'),
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='horario_checkout',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Horário da realização do Check-Out'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('CARD_CRED', 'Cartão de crédito'), ('CARD_DEB', 'Cartão de débito'), ('BOLETO', 'Boleto bancário'), ('TED', 'Transferência bancária'), ('A_VISTA', 'Pagamento a vista')], default='A_VISTA', max_length=10, verbose_name='Forma de pagamento')),
                ('status_reserva', models.CharField(default='AGUARDANDO', max_length=15, verbose_name='Status da reserva')),
                ('horario_checkin', models.DateTimeField(blank=True, null=True, verbose_name='Horário previsto para realização do Check-In')),
                ('horario_checkout', models.DateTimeField(auto_now=True, null=True, verbose_name='Horário previsto realização do Check-Out')),
                ('nome_hospede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospedes.hospede')),
                ('quartos', models.ManyToManyField(to='quartos.quarto', verbose_name='Quarto reservado pelo hóspede')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portaria.portaria', verbose_name='Atendente responsável pela reserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.AddField(
            model_name='hospede',
            name='reservas',
            field=models.ManyToManyField(to='hospedes.reserva', verbose_name='Reservas do hóspede'),
        ),
    ]
