# Generated by Django 5.0.1 on 2024-02-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0004_alter_hospede_horario_checkout_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario_checkout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário previsto realização do Check-Out'),
        ),
    ]
