# Generated by Django 5.0.1 on 2024-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0006_alter_reserva_nome_hospede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='horario_checkin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário da realização do Check-In'),
        ),
    ]
